/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-30 15:28:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import Model.ServiceHistoryModel;
import java.util.ArrayList;
import java.util.List;
import Model.ServiceModel;
import Model.UserModel;

public final class service_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/components/commonscript.html", Long.valueOf(1643551269167L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Model.UserModel");
    _jspx_imports_classes.add("Model.ServiceHistoryModel");
    _jspx_imports_classes.add("Model.ServiceModel");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.DateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    ServiceModel service = (ServiceModel) request.getAttribute("service");
    UserModel user = (UserModel) session.getAttribute("user");
    
    Integer historyArrayCount = 0;
    ServiceHistoryModel serviceHistoryLast = null;
    List<String> labelArray = new ArrayList<>();
    List<Integer> dataArray = new ArrayList<>();
    
    if (!service.getHistoryList().isEmpty()) 
        historyArrayCount = service.getHistoryList().size();
    
    if (historyArrayCount > 0)
        serviceHistoryLast = service.getHistoryList().get(service.getHistoryList().size() - 1);

    if (serviceHistoryLast != null) {
        if (historyArrayCount < 15) {
            for (int i = 0; i < (15 - historyArrayCount); i++) {
                labelArray.add("''");
                dataArray.add(0);
            }
            for (int i = (service.getHistoryList().size() - historyArrayCount); i < (service.getHistoryList().size() - 1); i++) {
                labelArray.add("'" + dateFormat.format(service.getHistoryList().get(i).getCollectionTimestamp()) + "'");
                dataArray.add(service.getHistoryList().get(i).getComplaints());
            }
        } else {
            for (int i = (service.getHistoryList().size() - 15); i < (service.getHistoryList().size() - 1); i++) {
                labelArray.add("'" + dateFormat.format(service.getHistoryList().get(i).getCollectionTimestamp()) + "'");
                dataArray.add(service.getHistoryList().get(i).getComplaints());
            }
        }
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"Bootstrap/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"FontAwesome/css/all.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"styles/isdown.css\">\n");
      out.write("        \n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js\"></script>\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.js\"></script>\n");
      out.write("        \n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            function drawChart() {\n");
      out.write("                var dataArray = ");
      out.print( dataArray.toString() );
      out.write(";\n");
      out.write("                var labelArray = ");
      out.print( labelArray.toString() );
      out.write(";\n");
      out.write("                \n");
      out.write("                new Chart('isdown-chart', {\n");
      out.write("                    type: 'bar',\n");
      out.write("                    data: {\n");
      out.write("                        labels: labelArray,\n");
      out.write("                        datasets: [{\n");
      out.write("                            label: 'Reclamações',\n");
      out.write("                            data: dataArray,\n");
      out.write("                            borderColor: \"#333\",\n");
      out.write("                            backgroundColor: \"#888\"\n");
      out.write("                        }]\n");
      out.write("                    },\n");
      out.write("                    options: {\n");
      out.write("                        interaction: {\n");
      out.write("                            intersect: false,\n");
      out.write("                            mode: 'index'\n");
      out.write("                        },\n");
      out.write("                        plugins: {\n");
      out.write("                            legend: {\n");
      out.write("                                labels: {\n");
      out.write("                                    usePointStyle: true\n");
      out.write("                                },\n");
      out.write("                                position: 'right',\n");
      out.write("                                align: 'start',\n");
      out.write("                                display: false\n");
      out.write("                            }\n");
      out.write("                        },\n");
      out.write("                        scales: {\n");
      out.write("                            x: {\n");
      out.write("                                ticks: {\n");
      out.write("                                    source: 'auto',\n");
      out.write("                                    maxRotation: 0,\n");
      out.write("                                    autoSkip: true\n");
      out.write("                                }\n");
      out.write("                            },\n");
      out.write("                            y: {\n");
      out.write("                                beginAtZero: true,\n");
      out.write("                                stacked: false\n");
      out.write("                            }\n");
      out.write("                        },\n");
      out.write("                        responsive: true,\n");
      out.write("                        fill: true,\n");
      out.write("                        radius: 0,\n");
      out.write("                        maintainAspectRatio: false\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("        <title>Is Down ?</title>\n");
      out.write("    </head>\n");
      out.write("    <body onload=\"drawChart()\">\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"index.jsp\">Is Down ?</a>\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Alterna navegação\">\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n");
      out.write("                <ul class=\"navbar-nav\">\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"index.jsp\">Página Inicial</a>\n");
      out.write("                    </li>\n");
      out.write("                    ");

                        if (user != null) {
                            if (user.getRole().getName().compareTo("Administrator") == 0) {
                    
      out.write("\n");
      out.write("                                <li class=\"nav-item\">\n");
      out.write("                                    <a class=\"nav-link\" href=\"User\">Usuários</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li class=\"nav-item\">\n");
      out.write("                                    <a class=\"nav-link\" href=\"Service\">Serviços</a>\n");
      out.write("                                </li>\n");
      out.write("                    ");

                                                    
                            }
                    
      out.write("\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"User?a=logout\">Logout</a>\n");
      out.write("                        </li>\n");
      out.write("                    ");

                        } else {
                    
      out.write("\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"User?a=login\">Login</a>\n");
      out.write("                        </li>\n");
      out.write("                    ");

                        }
                    
      out.write("\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <div class=\"album py-5\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <h3>");
      out.print( service.getName() );
      out.write("</h3>\n");
      out.write("                <br/>\n");
      out.write("                <br/>\n");
      out.write("                <div style=\"height: 500px;\" class=\"isdown-chart-div\">\n");
      out.write("                    <canvas class=\"isdown-chart-canvas\" id=\"isdown-chart\" ></canvas>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("<script src=\"JQuery/jquery-3.5.1.min.js\"></script>\n");
      out.write("<script src=\"JQuery/jquery.mask.min.js\"></script>\n");
      out.write("<script src=\"Popper/popper-2.8.4.min.js\"></script>\n");
      out.write("<script src=\"Bootstrap/js/bootstrap.min.js\"></script>");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
