/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2021-07-01 11:13:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.components;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.Usuario;
import dao.ContaDAO;
import dao.CategoriaDAO;
import java.util.ArrayList;
import models.Categoria;
import models.Conta;
import models.Lancamento;

public final class formLancamento_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.Usuario");
    _jspx_imports_classes.add("models.Conta");
    _jspx_imports_classes.add("dao.CategoriaDAO");
    _jspx_imports_classes.add("models.Categoria");
    _jspx_imports_classes.add("dao.ContaDAO");
    _jspx_imports_classes.add("models.Lancamento");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Usuario usuario = (Usuario) session.getAttribute("usuario");
    Lancamento lancamento = (Lancamento) request.getAttribute("lancamento");
    CategoriaDAO categoriaDAO = new CategoriaDAO();
    ArrayList<Categoria> categorias = categoriaDAO.getAll();
    ContaDAO contaDAO = new ContaDAO();
    ArrayList<Conta> contas = contaDAO.getByUsuario(usuario.getId());

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"rounded border border-dark p-4 m-5\">\n");
      out.write("    <form method=\"POST\" action=\"LancamentoController\">                   \n");
      out.write("        <!-- ID (hidden) -->\n");
      out.write("        <input type=\"hidden\" class=\"form-control\" name=\"id\" id=\"id_novo_lancamento\" value=\"");
      out.print( lancamento.getId() );
      out.write("\">\n");
      out.write(" \n");
      out.write("        <!-- CONTA -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"conta\"><b> Conta </b></label>\n");
      out.write("            <select class=\"form-control\" id=\"id_conta\" name=\"id_conta\" required>\n");
      out.write("                <option id=\"\"></option>\n");
      out.write("                ");

                    for (int index = 0; index < contas.size(); index++) {
                        Conta conta = contas.get(index);
                
      out.write("\n");
      out.write("                    <option value=\"");
      out.print( conta.getId() );
      out.write('"');
      out.write(' ');
      out.print( conta.getId() == lancamento.getId_conta()? "selected" : "" );
      out.write('>');
      out.print( conta.getNome_conta());
      out.write("</option>\n");
      out.write("                ");

                    }
                
      out.write("\n");
      out.write("            </select>\n");
      out.write("        </div>\n");
      out.write("            \n");
      out.write("        <!-- CATEGORIA -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"categoria\"><b> Categoria </b></label>\n");
      out.write("            <select class=\"form-control\" id=\"id_conta\" name=\"id_categoria\" required>\n");
      out.write("                <option id=\"\"></option>\n");
      out.write("                ");

                    for (int index = 0; index < categorias.size(); index++) {
                        Categoria categoria = categorias.get(index);
                
      out.write("\n");
      out.write("                    <option value=\"");
      out.print( categoria.getId() );
      out.write('"');
      out.write(' ');
      out.print( categoria.getId() == lancamento.getId_categoria()? "selected" : "" );
      out.write('>');
      out.print( categoria.getDescricao());
      out.write("</option>\n");
      out.write("                ");

                    }
                
      out.write("\n");
      out.write("            </select>\n");
      out.write("        </div>\n");
      out.write("            \n");
      out.write("        <!-- VALOR -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"valor\"><b> Valor </b></label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"valor\" id=\"valor\" autocomplete=\"off\" value=\"");
      out.print( lancamento.getValor() == 0.0 ? "" : lancamento.getValor() );
      out.write("\" placeholder=\"Digite o Valor\" required>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- OPERACAO -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"operacao\"><b> Operação </b></label>\n");
      out.write("            <select class=\"form-control\" id=\"operacao\"  name=\"operacao\" required>\n");
      out.write("                <option value=\"C\" ");
      out.print( lancamento.getOperacao().equals("C") ? "selected" : "" );
      out.write("> Crédito </option>                 \n");
      out.write("                <option value=\"D\" ");
      out.print( lancamento.getOperacao().equals("D") ? "selected" : "" );
      out.write("> Débito </option>        \n");
      out.write("            </select>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- DATA -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"data\"><b> Data </b></label>\n");
      out.write("            <input type=\"text\" class=\"form-control data\" name=\"data\" id=\"data\" autocomplete=\"off\" value=\"");
      out.print( lancamento.getData() );
      out.write("\" placeholder=\"Digite a Data\" required>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- DESCRICAO -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"descricao\"><b> Descrição </b></label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"descricao\" id=\"descricao\" autocomplete=\"off\" value=\"");
      out.print( lancamento.getDescricao());
      out.write("\" placeholder=\"Digite a Descrição\">\n");
      out.write("        </div>\n");
      out.write("            \n");
      out.write("        <!-- BOTÃO -->\n");
      out.write("        <button type=\"submit\" class=\"btn btn-dark\"><i class=\"fas fa-save\"></i> Salvar </button>\n");
      out.write("    </form>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
