/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2021-06-26 13:35:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.components;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.UsuarioDAO;
import models.Conta;
import models.Usuario;

public final class formConta_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.Conta");
    _jspx_imports_classes.add("models.Usuario");
    _jspx_imports_classes.add("dao.UsuarioDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Conta conta = (Conta) request.getAttribute("conta");
    Usuario usuario = (Usuario) session.getAttribute("usuario");

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"rounded border border-dark p-4 m-5\">\n");
      out.write("    <form method=\"POST\" action=\"ContaController\">                   \n");
      out.write("        <!-- ID (hidden) -->\n");
      out.write("        <input type=\"hidden\" class=\"form-control\" name=\"id\" id=\"id_nova_conta\" value=\"");
      out.print( conta.getId() );
      out.write("\">\n");
      out.write("        \n");
      out.write("        <!-- USUARIO (hidden) -->\n");
      out.write("        <input type=\"hidden\" class=\"form-control\" name=\"id_usuario\" id=\"id_usuario\" value=\"");
      out.print( usuario.getId() );
      out.write("\">\n");
      out.write("            \n");
      out.write("        <!-- NOME DA CONTA -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"nome_conta\"><b> Nome da Conta </b></label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"nome_conta\" id=\"nome_conta\" autocomplete=\"off\" value=\"");
      out.print( conta.getNome_conta());
      out.write("\" placeholder=\"Digite o Nome da Conta\" required>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- BANCO -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"banco\"><b> Banco </b></label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"banco\" id=\"banco\" autocomplete=\"off\" value=\"");
      out.print( conta.getBanco() );
      out.write("\" placeholder=\"Digite o Banco\" required>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- AGENCIA -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"agencia\"><b> Agência </b></label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"agencia\" id=\"agencia\" autocomplete=\"off\" value=\"");
      out.print( conta.getAgencia() );
      out.write("\" placeholder=\"Digite a Agência\" required>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- CONTA CORRENTE -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"conta_corrente\"><b> Conta Corrente </b></label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"conta_corrente\" id=\"conta_corrente\" autocomplete=\"off\" value=\"");
      out.print( conta.getConta_corrente() );
      out.write("\" placeholder=\"Digite a Conta Corrente\" required>\n");
      out.write("        </div>\n");
      out.write("            \n");
      out.write("        <!-- BOTÃO -->\n");
      out.write("        <button type=\"submit\" class=\"btn btn-dark\"><i class=\"fas fa-save\"></i> Salvar </button>\n");
      out.write("    </form>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
